encyclopedia/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/", views.random_page, name="wiki"),
    path("wiki/<str:entry>", views.wiki, name="wiki_entry"),
    path("error", views.error, name="error"),
    path("search", views.search, name="search"),
    path("new/", views.new, name="new"),
    path("edit/<str:entry>", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import util
from django import forms

import random
import markdown2

class WikiForm(forms.Form):
    title = forms.CharField(label="Title", min_length=2, max_length=20)
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs=
        {"placeholder":"Use Markdown Syntax", "style":"height: 300px"}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def wiki(request, entry):
    entries = util.list_entries()
    if entry in entries:
        content = util.get_entry(entry)
        HTML_format = markdown2.markdown(content)
        return render(request, "encyclopedia/wiki.html", {
            "title":entry,
            "content":HTML_format
        })
    else:
        return HttpResponseRedirect("/error")

def error(request):
    return render(request, "encyclopedia/error.html")


def search(request):
    if request.method=="GET":
        query = request.GET.get("q")
        if query == "" or query is None:
            return HttpResponseRedirect(reverse("index"))
    else:
        return HttpResponseRedirect(reverse("index"))

    if util.get_entry(query) is not None:
        return redirect(wiki, query)

    entries = util.list_entries()
    result = []
    for e in entries:
        if query.lower() in e.lower() or e.lower() in query.lower():
            result.append(e)
    return render(request, "encyclopedia/search.html",{
        "query": query,
        "result": result,
        "is_found" : len(result) > 0
    })

def new(request):
    if request.method=="POST":
        form = WikiForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if util.get_entry(title) is None:
                util.save_entry(title=title, content=content)
                return redirect(wiki, title)
            else:
                return render(request, "encyclopedia/new.html",{
                "form":form,
                "message": "Already Exist"
    })

    else:
        return render(request, "encyclopedia/new.html",{
        "form":WikiForm()
    })

def random_page(request):
    entries=util.list_entries()
    random_entry = random.choice(entries)
    return redirect(wiki, random_entry)

def edit(request, entry):
    content = util.get_entry(entry)
    if request.method=="POST":
        new_content = request.POST.get("content")
        util.save_entry(title=entry, content=new_content)
        return redirect(wiki, entry)

    if content:
        return render(request, "encyclopedia/edit.html",{
        "title": entry,
        "content" : util.get_entry(entry)
    })

    else:
        return HttpResponseRedirect(reverse('index'))

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Wiki | {{ title }}
{% endblock %}

{% block body %}

    <h1>EDIT WIKI</h1><br />
    {% if message %}
        <div id="message" style="color: red;">
           {{ message }}
        </div>
        <br />
    {% endif %}
    <form action="{% url 'edit' title %}" method="POST">
        {% csrf_token %}
        <p><label for="id_title">Title:</label> <input type="text" name="title" value="{{ title }}" id="id_title" readonly=""></p>
        <p><label for="id_content">Content:</label> <textarea name="content" style="height: 300px" required id="id_content">{{ content }}</textarea></p>
    <p>
    <input type="submit" value="save">
    </form>
    
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1 style="color:red;">The Requested Page Is Not Found!</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki_entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="/search" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Wiki
{% endblock %}

{% block body %}

    <h1>NEW WIKI</h1><br />
    {% if message %}
        <div id="message" style="color: red;">
           {{ message }}
        </div>
        <br />
    {% endif %}
    <form action="{% url 'new' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
    <p></p>
    <input type="submit" value="save">
    </form>
    
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Result | {{ query }}
{% endblock %}

{% block body %}
    {% if is_found %}
        <h1>Found Pages</h1>
        <ul>
            {% for r in result %}
                <li><a href="{% url 'wiki_entry' r %}">{{ r }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h1 style="color:red;">No Match found!</h1>

    {% endif %}
    
{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ content|safe }}
    <p style="margin-top: 40px;">
    	<a href="{% url 'edit' title %}">Edit</a>
{% endblock %}